name: AlexMerchen
favicon: null
layout_spectrum: 0.689596313983202
typography_spectrum: 0.5117045312654227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.865199311170727
  lightness: 0.21717151626944542
  saturation: 0.11377790127880871
  rhythmicContrast: 0.8318166905082762
purpose: []
