name: AlexMerchen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76062
title: New Haven House Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ced4e2'
    - '#b2b8c8'
    - '#918674'
    - '#2f3237'
    - '#4f473c'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
