name: Alex Merchen
favicon: null
layout_spectrum: 0.49213
typography_spectrum: 0.20794
title: New Haven House Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ced4e2'
    - '#b2b8c8'
    - '#918674'
    - '#2f3237'
    - '#4f473c'
  brandStrength: 0.75
  lightness: 0.125
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
